name: dontlieme_task
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^6.2.0
  flutter_screenutil: ^5.7.0

  #Riverpod
  flutter_riverpod: ^2.3.2

  #DI
  get_it: ^7.2.0
  injectable: ^2.1.0

  #image
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  injectable_generator: ^2.1.4
  flutter_gen_runner: ^5.4.0

flutter_gen:
  output: lib/gen/ 
  line_length: 80 # 

  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/svgs/
    - assets/pngs/
